### ISSUE TITLE
Invalid escape sequence error

### ISSUE THREAD

**Issue by alexangas** [ae0j/discogs-advanced-sorter#4]
Hello, i'm interested in trying out this project. I followed the instructions for installation but when executing `flask run` get the error:

```
process.py:243: SyntaxWarning: invalid escape sequence '\d'
  price_numeric = float(re.sub("[^\d\.]", "", price_value))
```

Any ideas?

**Comment by ae0j** [comment]
Hi, thanks for the report. It should be fixed now. Could you please try again?

**Comment by alexangas** [comment]
All fixed, thank you 🙂
